# Generated by Django 3.2 on 2023-09-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttier',
            old_name='can_generate_expiring_liks',
            new_name='can_generate_expiring_links',
        ),
    ]
