# Generated by Django 3.2 on 2023-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
