# Generated by Django 3.2 on 2023-10-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_expiringlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiringLink',
        ),
    ]
