# Generated by Django 3.2 on 2023-10-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_delete_expiringlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_200',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_400',
        ),
    ]
