# Generated by Django 3.2 on 2023-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_auto_20231001_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
