# Generated by Django 3.2 on 2023-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0006_alter_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiring_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
